# Generated by Django 2.2.1 on 2019-06-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='yearsExperience',
            new_name='aniosExperiencia',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='ap_mat',
            new_name='apellidoMat',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='ap_pat',
            new_name='apellidoPat',
        ),
    ]
