# Generated by Django 2.2.1 on 2019-05-25 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('ap_pat', models.CharField(max_length=100)),
                ('ap_mat', models.CharField(max_length=100)),
                ('matricula', models.IntegerField()),
                ('materia', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=50)),
                ('fechaNacimiento', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('profesorAsig', models.ForeignKey(on_delete=models.SET(-1), to='Profesor.Profesor')),
            ],
            options={
                'db_table': 'Alumno',
            },
        ),
    ]
